"""Export one customer of the LATAM Bank dummy dataset to a JSON fixture.

The "Mis productos" section reads this fixture until the back exposes the
customer's data. Usage (from front/):

    python3 scripts/export-demo-customer.py [CUSTOMER_ID]

data/dummy_output is generated by data/generate_dummy_data.py; set DATA_DIR
to read it from another checkout.
"""

import csv
import json
import os
import sys
from pathlib import Path

DATA = Path(os.environ.get("DATA_DIR", Path(__file__).resolve().parents[2] / "data" / "dummy_output"))
OUT = Path(__file__).resolve().parents[1] / "src" / "mocks" / "demo-customer.json"

CUSTOMER_FIELDS = [
    "customer_id", "document_number", "document_type", "first_name", "last_name",
    "date_of_birth", "email", "mobile_phone", "address", "city", "state", "country",
    "segment", "credit_score", "estimated_monthly_income", "occupation",
    "marital_status", "registration_date", "customer_status",
]
PRODUCT_FIELDS = [
    "product_id", "product_type", "product_number", "currency", "current_balance",
    "credit_limit", "interest_rate", "opening_date", "expiration_date",
    "product_status", "opening_channel", "days_past_due", "last_transaction_date",
]
TRANSACTION_FIELDS = [
    "transaction_id", "transaction_date", "product_id", "transaction_type",
    "transaction_category", "amount", "currency", "channel", "merchant_name",
    "transaction_city", "transaction_status",
]
NUMBERS = {"current_balance", "credit_limit", "interest_rate", "days_past_due",
           "amount", "credit_score", "estimated_monthly_income"}


def read(table: str) -> list[dict]:
    with open(DATA / table / f"{table}.csv", newline="") as f:
        return list(csv.DictReader(f))


def pick(row: dict, fields: list[str]) -> dict:
    out = {}
    for field in fields:
        value = row.get(field) or None
        if value is not None and field in NUMBERS:
            value = float(value)
        out[field] = value
    return out


def main(customer_id: str) -> None:
    customer = next(c for c in read("customers") if c["customer_id"] == customer_id)
    products = [p for p in read("products") if p["customer_id"] == customer_id]
    transactions = [t for t in read("transactions") if t["customer_id"] == customer_id]
    transactions.sort(key=lambda t: t["transaction_date"], reverse=True)
    fixture = {
        "source": f"data/dummy_output (LATAM Bank dummy), {customer_id}",
        "customer": pick(customer, CUSTOMER_FIELDS),
        "products": [pick(p, PRODUCT_FIELDS) for p in products],
        "transactions": [pick(t, TRANSACTION_FIELDS) for t in transactions],
    }
    OUT.write_text(json.dumps(fixture, ensure_ascii=False, indent=2) + "\n")
    print(f"{OUT}: {len(products)} products, {len(transactions)} transactions")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "CUS00000322")
