import type { Lang } from './i18n';

const es = {
  title: 'Inteligencia de fraude',
  subtitle: 'Datos, predicciones y revisión humana en una sola vista.',
  overview: 'Panorama de datos',
  operations: 'Operación',
  model: 'Evaluación ML',
  experimental: 'Modelo experimental',
  refresh: 'Actualizar',
  refreshing: 'Actualizando…',
  loading: 'Preparando el análisis de fraude…',
  error: 'No pudimos cargar el dashboard.',
  retry: 'Reintentar',
  snapshot: 'Snapshot del dataset',
  published: 'Evidencia publicada',
  live: 'Reclamos registrados',
  total: 'Transacciones',
  labels: 'Etiquetas de fraude',
  prevalence: 'Prevalencia histórica',
  cleanIds: 'IDs completos y únicos',
  labelNote:
    'Etiquetas del dataset sintético; su origen aún requiere validación.',
  ratioNote: 'Aproximadamente 1 etiqueta de fraude por cada',
  transactions: 'transacciones',
  trend: 'Actividad histórica',
  trendNote: 'Meses de entrenamiento y validación · hasta diciembre de 2025.',
  volume: 'Volumen',
  rate: 'Tasa de etiquetas',
  country: 'País',
  channel: 'Canal',
  type: 'Tipo',
  segments: 'Distribución por segmento',
  segmentNote:
    'El volumen no implica mayor riesgo. Compara también la tasa de etiquetas.',
  quality: 'Calidad y disponibilidad',
  missing: 'Ausente',
  complete: 'Completo',
  qualityNote:
    'Silver v1 · disponibilidad de campos, independiente de la calidad predictiva.',
  qualityLabels: {
    merchant_category: 'Categoría del comercio',
    amount_usd_raw: 'Monto USD original',
    amount_usd_normalized: 'Monto USD normalizado',
    labels: 'Etiqueta is_fraud',
    ids: 'ID de transacción',
  },
  insight: 'Lecturas clave',
  concentration: 'Concentración de actividad',
  concentrated:
    'del volumen está en el país con más transacciones. Esto describe actividad, no fraude confirmado.',
  imbalance: 'Fraude poco frecuente',
  imbalanceText:
    'La exactitud global puede parecer alta incluso ignorando todos los fraudes. Evalúa precisión y recall.',
  normalization: 'Normalización que recupera cobertura',
  normalizationText:
    'En USD se usa el monto original; en otras monedas, la conversión disponible. La ausencia baja de',
  to: 'a',
  currencies: 'Monedas de origen',
  currencyNote:
    'Las cantidades monetarias no se suman entre monedas distintas.',
  period: 'Período de reclamos',
  today: 'Hoy',
  week: '7 días',
  month: '30 días',
  complaints: 'Reclamos recibidos',
  coverage: 'Cobertura de predicción',
  alerts: 'Sobre el umbral ML',
  open: 'Pendientes de cierre',
  complaintNote:
    'Eventos de derivación por reclamo, según su fecha de registro. Una conversación puede generar varios eventos.',
  alertsNote:
    'Señales experimentales para revisión; no son fraudes confirmados.',
  unknown: 'Sin datos',
  noCases: 'Todavía no hay reclamos en este período.',
  noCasesText:
    'Cuando un cliente confirme un reclamo, su evaluación aparecerá aquí.',
  unavailable:
    'La base de reclamos no está disponible. La evidencia histórica sigue accesible.',
  operationalError:
    'No se pudo consultar la operación. Actualiza para reintentar; no se muestran ceros como datos reales.',
  daily: 'Reclamos por día',
  scored: 'Con predicción',
  without: 'Sin predicción disponible',
  scoreDistribution: 'Distribución del índice ML',
  scoreNote: 'Escala 0–100. El índice no es una probabilidad validada.',
  categories: 'Motivos del reclamo',
  complaintTypes: {
    not_recognized: 'Cargo no reconocido',
    duplicate_charge: 'Cobro duplicado',
    different_amount: 'Monto diferente',
    other: 'Otro / sin clasificar',
  },
  workflow: 'Confirmación del cliente → predicción → revisión humana',
  workflowText:
    'Cerrar la atención no confirma ni descarta fraude. Aún no se registran etiquetas verificadas del resultado.',
  validation: 'Validación temporal',
  validationPeriod:
    'Julio–diciembre de 2025 · 743.909 transacciones · 699 etiquetas de fraude',
  precision: 'Precisión de alertas',
  recall: 'Fraudes recuperados (recall)',
  ap: 'Average precision',
  roc: 'ROC AUC',
  precisionNote: 'Alertas que coinciden con etiquetas positivas.',
  recallNote: 'Etiquetas positivas que el modelo logra señalar.',
  modelNote:
    'El modelo genera predicciones dentro del agente. Su desempeño actual exige revisión humana en todos los casos.',
  compare: 'Modelos y evidencia',
  serving: 'En la app · experimental',
  rejected: 'Challenger descartado',
  silverCaveat:
    'V8 usa Silver; su replay difiere ligeramente de Gold. V9 reproduce exactamente el baseline Gold V7.',
  modelColumn: 'Modelo',
  result: 'Resultado',
  trueAlerts: 'Aciertos / alertas',
  confusion: 'Qué significan las alertas de V7',
  truePositive: 'Positivos detectados',
  falsePositive: 'Alertas sin etiqueta de fraude',
  falseNegative: 'Fraudes no detectados',
  trueNegative: 'Negativos sin alerta',
  monthly: 'Precisión por mes',
  monthlyNote: 'V7 frente a V9 · mismo período y fuente Gold.',
  moreData: 'Más cobertura, sin ganancia validada',
  moreDataText:
    'La cobertura de historial digital pasó de 7 a 90 días, pero no mejoró la precisión. V7 sigue en la app.',
  threshold: 'Umbral de revisión',
  thresholdNote:
    'Índice ML, no precisión ni probabilidad. Fijado antes de la validación.',
  controls: 'Controles del modelo',
  human: 'Revisión humana obligatoria',
  automatic: 'Decisiones automáticas desactivadas',
  sealed: 'Test final sin evaluar',
  leakage: 'fraud_score excluido por leakage',
  source: 'Fuente y trazabilidad',
  historical: 'Evidencia histórica; no es un feed en tiempo real.',
  details: 'Ver datos del gráfico',
  evidence: 'Evidencia reproducible',
  selected: 'Mes seleccionado',
  count: 'Cantidad',
  labelCount: 'Etiquetas',
  noScore: 'No hay predicciones disponibles para graficar.',
  audit: 'Integridad temporal y trazabilidad',
  auditNote:
    'Auditoría del período anterior a julio de 2025 · no representa todo el dataset.',
  registrationAfter: 'Transacciones anteriores al registro del cliente',
  openingAfter: 'Transacciones anteriores a la apertura del producto',
  digitalUnlinked: 'Eventos digitales sin cliente vinculable',
  processingBefore: 'Eventos procesados antes de su fecha de evento',
  auditAction:
    'Revisar con el proveedor el significado de las fechas y cómo se asignó is_fraud antes de promover el modelo. Estas señales no confirman fraude.',
  trainingCohort: 'transacciones auditadas',
  digitalCohort: 'eventos auditados',
};
type Copy = {
  [K in keyof typeof es]: (typeof es)[K] extends string
    ? string
    : Record<string, string>;
};
const pt: Copy = {
  title: 'Inteligência de fraude',
  subtitle: 'Dados, previsões e revisão humana em uma só visão.',
  overview: 'Panorama dos dados',
  operations: 'Operação',
  model: 'Avaliação ML',
  experimental: 'Modelo experimental',
  refresh: 'Atualizar',
  refreshing: 'Atualizando…',
  loading: 'Preparando a análise de fraude…',
  error: 'Não foi possível carregar o dashboard.',
  retry: 'Tentar novamente',
  snapshot: 'Snapshot do dataset',
  published: 'Evidência publicada',
  live: 'Reclamações registradas',
  total: 'Transações',
  labels: 'Rótulos de fraude',
  prevalence: 'Prevalência histórica',
  cleanIds: 'IDs completos e únicos',
  labelNote: 'Rótulos do dataset sintético; sua origem ainda requer validação.',
  ratioNote: 'Aproximadamente 1 rótulo de fraude a cada',
  transactions: 'transações',
  trend: 'Atividade histórica',
  trendNote: 'Meses de treinamento e validação · até dezembro de 2025.',
  volume: 'Volume',
  rate: 'Taxa de rótulos',
  country: 'País',
  channel: 'Canal',
  type: 'Tipo',
  segments: 'Distribuição por segmento',
  segmentNote:
    'Volume não implica maior risco. Compare também a taxa de rótulos.',
  quality: 'Qualidade e disponibilidade',
  missing: 'Ausente',
  complete: 'Completo',
  qualityNote:
    'Silver v1 · disponibilidade dos campos, independente da qualidade preditiva.',
  qualityLabels: {
    merchant_category: 'Categoria do estabelecimento',
    amount_usd_raw: 'Valor USD original',
    amount_usd_normalized: 'Valor USD normalizado',
    labels: 'Rótulo is_fraud',
    ids: 'ID da transação',
  },
  insight: 'Leituras principais',
  concentration: 'Concentração de atividade',
  concentrated:
    'do volume está no país com mais transações. Isso descreve atividade, não fraude confirmado.',
  imbalance: 'Fraude pouco frequente',
  imbalanceText:
    'A acurácia global pode parecer alta mesmo ignorando todas as fraudes. Avalie precisão e recall.',
  normalization: 'Normalização que recupera cobertura',
  normalizationText:
    'Em USD usa-se o valor original; nas outras moedas, a conversão disponível. A ausência cai de',
  to: 'para',
  currencies: 'Moedas de origem',
  currencyNote: 'Valores monetários não são somados entre moedas diferentes.',
  period: 'Período das reclamações',
  today: 'Hoje',
  week: '7 dias',
  month: '30 dias',
  complaints: 'Reclamações recebidas',
  coverage: 'Cobertura de previsão',
  alerts: 'Acima do limiar ML',
  open: 'Pendentes de encerramento',
  complaintNote:
    'Eventos de encaminhamento por reclamação, segundo a data de registro. Uma conversa pode gerar vários eventos.',
  alertsNote: 'Sinais experimentais para revisão; não são fraudes confirmadas.',
  unknown: 'Sem dados',
  noCases: 'Ainda não há reclamações neste período.',
  noCasesText:
    'Quando um cliente confirmar uma reclamação, sua avaliação aparecerá aqui.',
  unavailable:
    'A base de reclamações não está disponível. A evidência histórica permanece acessível.',
  operationalError:
    'Não foi possível consultar a operação. Atualize para tentar novamente; zeros não são apresentados como dados reais.',
  daily: 'Reclamações por dia',
  scored: 'Com previsão',
  without: 'Sem previsão disponível',
  scoreDistribution: 'Distribuição do índice ML',
  scoreNote: 'Escala 0–100. O índice não é uma probabilidade validada.',
  categories: 'Motivos da reclamação',
  complaintTypes: {
    not_recognized: 'Cobrança não reconhecida',
    duplicate_charge: 'Cobrança duplicada',
    different_amount: 'Valor diferente',
    other: 'Outro / sem classificação',
  },
  workflow: 'Confirmação do cliente → previsão → revisão humana',
  workflowText:
    'Encerrar o atendimento não confirma nem descarta fraude. Rótulos verificados do resultado ainda não são registrados.',
  validation: 'Validação temporal',
  validationPeriod:
    'Julho–dezembro de 2025 · 743.909 transações · 699 rótulos de fraude',
  precision: 'Precisão dos alertas',
  recall: 'Fraudes recuperadas (recall)',
  ap: 'Average precision',
  roc: 'ROC AUC',
  precisionNote: 'Alertas que coincidem com rótulos positivos.',
  recallNote: 'Rótulos positivos que o modelo consegue sinalizar.',
  modelNote:
    'O modelo gera previsões dentro do agente. Seu desempenho atual exige revisão humana em todos os casos.',
  compare: 'Modelos e evidências',
  serving: 'No app · experimental',
  rejected: 'Challenger descartado',
  silverCaveat:
    'V8 usa Silver; seu replay difere ligeiramente de Gold. V9 reproduz exatamente o baseline Gold V7.',
  modelColumn: 'Modelo',
  result: 'Resultado',
  trueAlerts: 'Acertos / alertas',
  confusion: 'O que significam os alertas do V7',
  truePositive: 'Positivos detectados',
  falsePositive: 'Alertas sem rótulo de fraude',
  falseNegative: 'Fraudes não detectadas',
  trueNegative: 'Negativos sem alerta',
  monthly: 'Precisão por mês',
  monthlyNote: 'V7 versus V9 · mesmo período e fonte Gold.',
  moreData: 'Mais cobertura, sem ganho validado',
  moreDataText:
    'A cobertura do histórico digital passou de 7 para 90 dias, mas não melhorou a precisão. V7 permanece no app.',
  threshold: 'Limiar de revisão',
  thresholdNote:
    'Índice ML, não precisão nem probabilidade. Fixado antes da validação.',
  controls: 'Controles do modelo',
  human: 'Revisão humana obrigatória',
  automatic: 'Decisões automáticas desativadas',
  sealed: 'Teste final sem avaliação',
  leakage: 'fraud_score excluído por leakage',
  source: 'Fonte e rastreabilidade',
  historical: 'Evidência histórica; não é um feed em tempo real.',
  details: 'Ver dados do gráfico',
  evidence: 'Evidência reproduzível',
  selected: 'Mês selecionado',
  count: 'Quantidade',
  labelCount: 'Rótulos',
  noScore: 'Não há previsões disponíveis para o gráfico.',
  audit: 'Integridade temporal e rastreabilidade',
  auditNote:
    'Auditoria do período anterior a julho de 2025 · não representa todo o dataset.',
  registrationAfter: 'Transações anteriores ao cadastro do cliente',
  openingAfter: 'Transações anteriores à abertura do produto',
  digitalUnlinked: 'Eventos digitais sem cliente vinculável',
  processingBefore: 'Eventos processados antes da data do evento',
  auditAction:
    'Revisar com o fornecedor o significado das datas e como is_fraud foi atribuído antes de promover o modelo. Esses sinais não confirmam fraude.',
  trainingCohort: 'transações auditadas',
  digitalCohort: 'eventos auditados',
};
export function fraudCopy(lang: Lang): Copy {
  return lang === 'pt' ? pt : es;
}
